# Generated by Django 4.2.26 on 2025-12-01 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Palette')),
                ('primary_color', models.CharField(default='#007bff', help_text='Formato esadecimale (es. #007bff)', max_length=7, verbose_name='Colore Primario')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='Colore Secondario')),
                ('accent_color', models.CharField(default='#28a745', max_length=7, verbose_name='Colore Accento')),
                ('text_color', models.CharField(default='#212529', max_length=7, verbose_name='Colore Testo')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Colore Sfondo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Palette Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Palette Colori',
                'verbose_name_plural': 'Palette Colori',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Oggetto')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('is_read', models.BooleanField(default=False, verbose_name='Letto')),
            ],
            options={
                'verbose_name': 'Messaggio',
                'verbose_name_plural': 'Messaggi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Posizione')),
                ('company', models.CharField(max_length=200, verbose_name='Azienda')),
                ('location', models.CharField(max_length=100, verbose_name='Luogo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('start_date', models.DateField(verbose_name='Data Inizio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Fine')),
                ('is_current', models.BooleanField(default=False, verbose_name='Posizione Attuale')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Esperienza',
                'verbose_name_plural': 'Esperienze',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descrizione Completa')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descrizione Breve')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Immagine Principale')),
                ('technologies', models.CharField(help_text='Separare con virgola (es. Python, Django, React)', max_length=500, verbose_name='Tecnologie')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='URL Progetto')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='URL GitHub')),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('fullstack', 'Full Stack')], default='web', max_length=20, verbose_name='Categoria')),
                ('featured', models.BooleanField(default=False, verbose_name='In Evidenza')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Skill')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('devops', 'DevOps'), ('tools', 'Tools'), ('database', 'Database')], default='backend', max_length=20, verbose_name='Categoria')),
                ('proficiency', models.IntegerField(default=3, help_text='Da 1 a 5 stelle', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Livello')),
                ('icon', models.CharField(default='fas fa-code', help_text='Es. fas fa-python, fab fa-js', max_length=50, verbose_name='Icona FontAwesome')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Portfolio', max_length=200, verbose_name='Titolo Sito')),
                ('site_description', models.TextField(default='Portfolio di un Web & Mobile Developer', verbose_name='Descrizione Sito')),
                ('author_name', models.CharField(default='Developer', max_length=100, verbose_name='Nome Autore')),
                ('author_bio', models.TextField(blank=True, verbose_name='Bio Autore')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Foto Profilo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Località')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Es. {"github": "https://github.com/...", "linkedin": "..."}', verbose_name='Link Social')),
                ('current_palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.colorpalette', verbose_name='Palette Attiva')),
            ],
            options={
                'verbose_name': 'Impostazioni Sito',
                'verbose_name_plural': 'Impostazioni Sito',
            },
        ),
    ]
