# Generated by Django 5.2.8 on 2025-12-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Corso/Diploma')),
                ('institution', models.CharField(max_length=200, verbose_name='Istituto/Scuola')),
                ('hours', models.IntegerField(blank=True, help_text='Esempio: 100', null=True, verbose_name='Ore Totali')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('start_date', models.DateField(verbose_name='Data Inizio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Fine')),
                ('is_current', models.BooleanField(default=False, verbose_name='In Corso')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Formazione',
                'verbose_name_plural': 'Formazione',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='File CV (PDF)'),
        ),
    ]
