# Generated by Django 5.2.8 on 2025-12-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_sitesettings_cv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='current_palette',
        ),
        migrations.DeleteModel(
            name='ColorPalette',
        ),
    ]
