# Generated by Django 5.2.8 on 2025-12-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_sitesettings_current_palette_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Formazione', 'verbose_name_plural': 'Formazione'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
    ]
