# Generated by Django 5.2.8 on 2025-12-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_education_options_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Certificazione')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Ente Emittente')),
                ('issue_date', models.DateField(verbose_name='Data di Rilascio')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='Immagine Certificato')),
                ('verification_url', models.URLField(blank=True, null=True, verbose_name='URL di Verifica')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Certificazione',
                'verbose_name_plural': 'Certificazioni',
                'ordering': ['-issue_date', 'order'],
            },
        ),
    ]
