# Generated by Django 6.0 on 2025-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Foto Homepage'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Foto Profilo (About)'),
        ),
    ]
